# Generated by Django 3.1.4 on 2020-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('types', models.CharField(choices=[('S', 'Square'), ('R', 'Regular')], max_length=1)),
                ('toppings', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
    ]
