# Generated by Django 3.1.4 on 2020-12-18 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
